version: '2'
services:
  neo4j:
    image: neo4j:4.4.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/neo4j
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
